import React, { useState } from "react";

const Faq = () => {
  return (
    <section className="relative z-20 overflow-hidden bg-white pb-12 pt-20 dark:bg-dark lg:pb-[90px] lg:pt-[120px]">
      <div className="container mx-auto" >
        <div className="-mx-4 flex flex-wrap" id="faq">
          <div className="w-full px-4">
            <div className="mx-auto mb-[60px] max-w-[520px] text-center lg:mb-20">
              <span className="mb-2 block text-lg font-semibold text-primary">
                FAQ
              </span>
              <h2 className="mb-4 text-3xl font-bold text-dark dark:text-white sm:text-[40px]/[48px]">
                Any Questions? Look Here
              </h2>
              <p className="text-base text-body-color dark:text-dark-6">
              "Welcome to our FAQ section! Find quick answers to your questions about accessing and managing your personal health records. Browse below, and reach out if you need further assistance!"
              </p>
            </div>
          </div>
        </div>

        <div className="-mx-4 flex flex-wrap">
          <div className="w-full px-4 lg:w-1/2">
            <AccordionItem
              header="How secure is my personal health information within this system?"
              text="Your personal health information within this system is highly secure. We employ robust security measures to safeguard your data against unauthorized access, ensuring confidentiality and privacy. These measures include encryption protocols to protect data during transmission and storage, stringent access controls, regular security audits, and compliance with industry standards and regulations such as HIPAA (Health Insurance Portability and Accountability Act). Additionally, our system is continuously monitored and updated to address emerging security threats, providing you with peace of mind regarding the safety and integrity of your health information."
            />
            <AccordionItem
              header="How do I log in securely to access my personal health records?"
              text="To log in securely and access your personal health records, follow these steps: 

              1. Visit the login page of the personal health records system.  
              2. Enter your username, which is typically your email address associated with your account.
              3. Enter your password, ensuring it is a strong and unique combination of characters.
              4. Click on the Log In button to proceed.

              Upon successful authentication, you will gain access to your personal health records, where you can view and manage your health information securely. It's important to keep your login credentials confidential and to log out of your account after each session to maintain security."
            />
            <AccordionItem
              header="Is there an option for two-factor authentication to enhance security?"
              text="Yes, there is an option for two-factor authentication to enhance security. With two-factor authentication enabled, in addition to entering your password, you'll be required to provide a second form of verification, such as a unique code sent to your mobile device or generated by an authenticator app. This additional layer of security helps prevent unauthorized access to your personal health records, enhancing overall system security."
            />
          </div>
          <div className="w-full px-4 lg:w-1/2">
            <AccordionItem
              header="Can I control who has access to my health information within the system?"
              text="Yes, you have full control over who has access to your health information within the system. You can manage access permissions and specify which individuals or healthcare providers are authorized to view your records. This ensures that your health information remains private and secure, with access limited to only those you trust and approve."
            />
            <AccordionItem
              header="Can I share my health records with my healthcare provider using this system?"
              text="Yes, you can share your health records with your healthcare provider using this system. However, you need to grant access to your healthcare provider to view your records securely. Once access is granted, your healthcare provider will be able to access the relevant health information stored within the system, ensuring seamless communication and coordination of your healthcare needs."
            />
            <AccordionItem
              header="What do I do if I encounter technical issues while using the system?"
              text="If you encounter technical issues while using the system, you can contact EagleSoftware's support team to resolve your concerns. Our dedicated support staff is available to assist you with any technical difficulties you may encounter, ensuring a smooth and seamless experience with our system. Please feel free to reach out to us via email, phone, or our online support portal, and we'll promptly address your issues and provide the necessary assistance to resolve them. Your satisfaction and success with our system are our top priorities, and we're here to support you every step of the way."
            />
          </div>
        </div>
      </div>

      <div className="absolute bottom-0 right-0 z-[-1]">
        <svg
          width="1440"
          height="886"
          viewBox="0 0 1440 886"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            opacity="0.5"
            d="M193.307 -273.321L1480.87 1014.24L1121.85 1373.26C1121.85 1373.26 731.745 983.231 478.513 729.927C225.976 477.317 -165.714 85.6993 -165.714 85.6993L193.307 -273.321Z"
            fill="url(#paint0_linear)"
          />
          <defs>
            <linearGradient
              id="paint0_linear"
              x1="1308.65"
              y1="1142.58"
              x2="602.827"
              y2="-418.681"
              gradientUnits="userSpaceOnUse"
            >
              <stop stop-color="#3056D3" stop-opacity="0.36" />
              <stop offset="1" stop-color="#F5F2FD" stop-opacity="0" />
              <stop offset="1" stop-color="#F5F2FD" stop-opacity="0.096144" />
            </linearGradient>
          </defs>
        </svg>
      </div>
    </section>
  );
};

export default Faq;

const AccordionItem = ({ header, text }) => {
  const [active, setActive] = useState(false);

  const handleToggle = (event) => {
    //event.preventDefault();
    setActive(!active);
  };
  return (
    <div className="mb-8 w-full rounded-lg bg-white p-4 shadow-[0px_20px_95px_0px_rgba(201,203,204,0.30)] dark:bg-dark-2 dark:shadow-[0px_20px_95px_0px_rgba(0,0,0,0.30)] sm:p-8 lg:px-6 xl:px-8">
      <button
        className={`faq-btn flex w-full text-left`}
        onClick={() => handleToggle()}
      >
        <div className="mr-5 flex h-10 w-full max-w-[40px] items-center justify-center rounded-lg bg-primary/5 text-primary dark:bg-white/5">
          <svg
            className={`fill-primary stroke-primary duration-200 ease-in-out ${
              active ? "rotate-180" : ""
            }`}
            width="17"
            height="10"
            viewBox="0 0 17 10"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M7.28687 8.43257L7.28679 8.43265L7.29496 8.43985C7.62576 8.73124 8.02464 8.86001 8.41472 8.86001C8.83092 8.86001 9.22376 8.69083 9.53447 8.41713L9.53454 8.41721L9.54184 8.41052L15.7631 2.70784L15.7691 2.70231L15.7749 2.69659C16.0981 2.38028 16.1985 1.80579 15.7981 1.41393C15.4803 1.1028 14.9167 1.00854 14.5249 1.38489L8.41472 7.00806L2.29995 1.38063L2.29151 1.37286L2.28271 1.36548C1.93092 1.07036 1.38469 1.06804 1.03129 1.41393L1.01755 1.42738L1.00488 1.44184C0.69687 1.79355 0.695778 2.34549 1.0545 2.69659L1.05999 2.70196L1.06565 2.70717L7.28687 8.43257Z"
              fill=""
              stroke=""
            />
          </svg>
        </div>

        <div className="w-full">
          <h4 className="mt-1 text-lg font-semibold text-dark dark:text-white">
            {header}
          </h4>
        </div>
      </button>

      <div
        className={`pl-[62px] duration-200 ease-in-out ${
          active ? "block" : "hidden"
        }`}
      >
        <p className="py-3 text-base leading-relaxed text-body-color dark:text-dark-6">
          {text}
        </p>
      </div>
    </div>
  );
};
